### ISSUE TITLE
Automatically populate/update ecosystem-unbitrot issues

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/Blin#1]
See https://github.com/perl6/ecosystem-unbitrot/issues. It's a repo for investigating issues with modules that are bitrotted or failing their tests for other reasons. Looking [at this ticket](https://github.com/perl6/ecosystem-unbitrot/issues/319) it seems that people are still eager to investigate and fix modules, so let's provide them with all the info in an automated way.

**Comment by AlexDaniel** [comment]
@JJ wanna have a go at it? I can provide more info if needed.

**Comment by JJ** [comment]
I will definitely need it. If I got it correctly, what you're looking for is some bot that checks modules with issues and opens an issue in ecosystem-unbitrot to bitfreshen them?

**Comment by AlexDaniel** [comment]
> If I got it correctly, what you're looking for is some bot that checks modules with issues and opens an issue in ecosystem-unbitrot to bitfreshen them?

If you have a linux machine, you can try running something like this (you don't need a monster VM for that):

```
time PERL6LIB=lib bin/blin.p6 --old=2018.06 --new=2018.09 Foo::Regressed Foo::Regressed::Very Foo::Dependencies::B-on-A
```

If successful, it will produce some files in `output/`. Currently the format is not very machine readable, but that can be easily changed. It writes something like this:
```
Foo::Regressed – Fail, Bisected: 741ae6f4eda001e5196cd7e156e887e7279cf1d8
```

I'm looking for a script that'd take these files as an input and manage issues in ecosystem-unbitrot repo. Something similar to [populate-issues.p6](https://github.com/perl6/ecosystem-unbitrot/blob/master/populate-issues.p6) script, but I want it to edit issues instead of creating new ones if a ticket for a particular module already exists. If a ticket doesn't exist it should create one. If the issue is no longer there it should close the ticket.

**Comment by JJ** [comment]
El dom., 21 oct. 2018 a las 16:09, Aleks-Daniel Jakimenko-Aleksejev (<
notifications@github.com>) escribió:

> If I got it correctly, what you're looking for is some bot that checks
> modules with issues and opens an issue in ecosystem-unbitrot to bitfreshen
> them?
>
> If you have a linux machine, you can try running something like this (you
> don't need a monster VM for that):
>

I don't have any other kind.

time PERL6LIB=lib START_POINT=2018.06 END_POINT=2018.09 bin/blin.p6
Foo::Regressed Foo::Regressed::Very Foo::Dependencies::B-on-A
>
> If successful, it will produce some files in output/. Currently the
> format is not very machine readable, but that can be easily changed. It
> writes something like this:
>
> Foo::Regressed – Fail, Bisected: 741ae6f4eda001e5196cd7e156e887e7279cf1d8
>
> I'm looking for a script that'd take these files as an input and manage
> issues in ecosystem-unbitrot repo. Something similar to populate-issues.p6
> <https://github.com/perl6/ecosystem-unbitrot/blob/master/populate-issues.p6>
> script, but I want it to edit issues instead of creating new ones if a
> ticket for a particular module already exists. If a ticket doesn't exist it
> should create one. If the issue is no longer there it should close the
> ticket.
>
OK, that's not a problem. I can be done with the API too. It's much clear
now. I'll see what I can do.

**Comment by JJ** [comment]
There's edit-issues.p6 in the same repo. Would that work?

**Comment by AlexDaniel** [comment]
There's another ticket: #3. Also I'm working on it now. Closing.
